package GOALS::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:database=goals;host=localhost',
        user => 'goals',
        password => 'mysql1625',
    }
);

=head1 NAME

GOALS::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<GOALS>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Nick Prater

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
